image: gitlab.labranet.jamk.fi:4567/tt00cd77-python/tests:latest

stages:
  - test

test_job:
  stage: test
  script:
    - for i in {01..10}; do mv L$i /app/L$i; done
    - echo "Running tests..."
    - poetry run pytest /app/tests/ --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
 # Run tests using Poetry and pytest
  only:
    - main  # or branches as appropriate
  tags:
    - general
